### ISSUE TITLE
Runtime validation returns false negatives

### ISSUE THREAD

**Issue by karol-majewski** [petergombos/react-pledge#1]
Hey, just a little remark: the following statement

https://github.com/petergombos/react-pledge/blob/master/src/index.js#L57

Will always return `false`, because the bang `!` operator binds stronger than `instanceof`, and there is no thing that, when negated, would be an instance of Promise.

Try running this in your console to see what I'm talking about. ;-)

```js
/**
 * Something that's definitely not a Promise.
 */
const promise = false;

if (!promise instanceof Promise) {
    throw new Error('It was not a Promise!'); // Never runs
}
```

I believe the fix would be to:

```diff
- if (!promise instanceof Promise)
+ if (!(promise instanceof Promise))
```

**Comment by petergombos** [comment]
Thanks for pointing that out! I've actually ended up removing that check and just requiring the prop to be set as it turns out it's not straightforward validate promises. I've added tests, by the way, to help catch these bugs. Thanks for your input anyway.
