### ISSUE TITLE
The "build" folder is confusing 😕

### ISSUE THREAD

**Issue by juandc** [petergombos/react-pledge#2]
When you inspect the project at the first view, the `build` folder looks like the _compilation files_ folder. It is not until you inspect the project that you realize it is the utility folder, the _build utilities_.

So, why not change the name of the `build` folder to `utils` folder?

**Comment by petergombos** [comment]
Hey, thanks for your input!

I've used @ryanflorence 's https://github.com/reactions/component as a starting point when developing this package, I guess it's quite common to have build related stuff located in the build folder so I'm not planning to rename for now.
